/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderstandRouteImport } from './routes/understand'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BreakRouteImport } from './routes/break'
import { Route as IndexRouteImport } from './routes/index'

const UnderstandRoute = UnderstandRouteImport.update({
  id: '/understand',
  path: '/understand',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakRoute = BreakRouteImport.update({
  id: '/break',
  path: '/break',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/break': typeof BreakRoute
  '/build': typeof BuildRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/break': typeof BreakRoute
  '/build': typeof BuildRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/break': typeof BreakRoute
  '/build': typeof BuildRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/break' | '/build' | '/review' | '/settings' | '/understand'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/break' | '/build' | '/review' | '/settings' | '/understand'
  id:
    | '__root__'
    | '/'
    | '/break'
    | '/build'
    | '/review'
    | '/settings'
    | '/understand'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreakRoute: typeof BreakRoute
  BuildRoute: typeof BuildRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  UnderstandRoute: typeof UnderstandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/understand': {
      id: '/understand'
      path: '/understand'
      fullPath: '/understand'
      preLoaderRoute: typeof UnderstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/break': {
      id: '/break'
      path: '/break'
      fullPath: '/break'
      preLoaderRoute: typeof BreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreakRoute: BreakRoute,
  BuildRoute: BuildRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  UnderstandRoute: UnderstandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
